spring.datasource.url=jdbc:mysql://MYSQLHOST:MYSQLPORT/MYSQLDATABASE
spring.datasource.username=MYSQLUSER
spring.datasource.password=MYSQLPASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect




MYSQLHOST=mysql.railway.internal
MYSQLPORT=3306
MYSQLDATABASE=railway
MYSQLUSER=root
MYSQLPASSWORD=RXGPQUrBaDLBygZHqBRxBBRLdwfefjmm

git init
git add .
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/sanjayfreak/sanjayfreak.git
git push -u origin main
